name: CI/CD Deploy to Ubuntu

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  APP_HOME: /home/VlasikhaPlavanieWebsite

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Publish
        run: |
          dotnet restore
          dotnet publish -c Release -o ./publish

      - name: Install SSH key & known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy, link Files & config & restart
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          RELEASE_DIR=$APP_HOME/releases/$TIMESTAMP

          ssh -i ~/.ssh/id_rsa root@${{ secrets.HOST }} \
            "mkdir -p $RELEASE_DIR"

          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_rsa" \
            ./publish/ \
            root@${{ secrets.HOST }}:$RELEASE_DIR/

          ssh -i ~/.ssh/id_rsa root@${{ secrets.HOST }} \
            "ln -sfn $APP_HOME/shared/Files                                      $RELEASE_DIR/wwwroot/Files && \
             ln -sfn $APP_HOME/shared/images/competitions                        $RELEASE_DIR/wwwroot/images/competitions  && \
             ln -sfn $APP_HOME/shared/appsettings.Production.json                $RELEASE_DIR/appsettings.Production.json && \
             ln -sfn $RELEASE_DIR                                               $APP_HOME/current && \
             sudo systemctl restart kestrel.service"
